"""Storage protocol."""

from __future__ import annotations

from typing import Any, Protocol

from monitorit.awatch.storage.models import RequestRecord, TriggerHistoryRecord


class StorageProtocol(Protocol):
    async def setup(self) -> None: ...

    async def close(self) -> None: ...

    async def insert_request(self, record: RequestRecord) -> None: ...

    async def list_requests(
        self,
        *,
        limit: int = 100,
        offset: int = 0,
        status_code: int | None = None,
        method: str | None = None,
        path_contains: str | None = None,
        consumer_id: str | None = None,
        category: str | None = None,
        min_duration_ms: float | None = None,
    ) -> list[dict[str, Any]]: ...

    async def get_request(self, request_id: str) -> dict[str, Any] | None: ...

    async def endpoint_stats(self, hours: int = 24) -> list[dict[str, Any]]: ...

    async def traffic_timeline(self, hours: int = 24) -> list[dict[str, Any]]: ...

    async def consumer_stats(self, hours: int = 24) -> list[dict[str, Any]]: ...

    async def validation_heatmap(self, hours: int = 24) -> list[dict[str, Any]]: ...

    async def error_groups(self, hours: int = 24) -> list[dict[str, Any]]: ...

    async def insert_trigger_history(self, record: TriggerHistoryRecord) -> None: ...

    async def list_trigger_history(self, limit: int = 100) -> list[dict[str, Any]]: ...

    async def prune(self, max_requests: int, retention_hours: int) -> None: ...

    async def ping(self) -> bool: ...

    async def counts(self) -> dict[str, int]: ...

    async def observed_routes(self) -> set[str]: ...
